controlhub, #TRAC-421 : Fix to controlhub start script, and add more testing to check that fix definitely works     [CACTUS SVN 23825]

diff --git a/cactuscore/controlhub/scripts/controlhub_start b/cactuscore/controlhub/scripts/controlhub_start
--- a/cactuscore/controlhub/scripts/controlhub_start
+++ b/cactuscore/controlhub/scripts/controlhub_start
@@ -24,17 +24,24 @@ else
 fi
 
 if [ $CONTROLHUBSTATUS != 0 ]; then
-  echo -n "Starting Control Hub... "
+  echo "Starting Control Hub... "
   ${DIR}/erl_controlhub +zdbbl 2097151 +sbt db +scl false  +swt very_low -sname controlhub -setcookie ch_cookie -boot ${CONTROLHUB_ROOTDIR}/releases/2.0.0/start -config ${CONTROLHUB_ROOTDIR}/releases/2.0.0/sys -pa /opt/cactus/lib/erlang/lib/*/ebin/ -detached
-  sleep 1
-  ${DIR}/controlhub_status > /dev/null
-  if [ $? = 0 ]; then
-    echo "ok"
-  else
-    echo "FAILED!"
-    echo "    ==> see '/var/log/controlhub.log' for more info"
-    exit 4
-  fi
+  for i in `seq 1 10`; do
+    sleep 1
+    ${DIR}/controlhub_status > /dev/null
+    if [ $? = 0 ]; then
+      echo "ok"
+      exit 0
+    fi
+    echo "N.B: ControlHub not up after $i attempts of controlhub_status."
+  done
+
+  # Only get here if controlhub didn't start after N seconds
+  ${DIR}/controlhub_stop > /dev/null
+  echo "FAILED!"
+  echo "    ==> see '/var/log/controlhub.log' for more info"
+  exit 4
+
 else
   echo "Control Hub already running!"
 fi
